TITLE "PROGRAM TO PRINT HELLO WORLD IN ALP."
.MODEL SMALL
.STACK
.DATA
    VAL DW 'HELLO WORLD $'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    MOV DX, OFFSET VAL
    MOV AH, 09H
    INT 21H
    
    MOV AX, 4C00H
    INT 21H
    
    MAIN ENDP
END MAIN